contact_links:
  - name: ğŸ“¢ Feedback
    url: https://step.ci/feedback
    about: Leave your feedback
  - name: ğŸ™‹ GitHub Community
    url: https://github.com/stepci/stepci/discussions
    about: Please ask and answer questions here
  - name: ğŸ“¨ Newsletter
    url: https://stepci.com/#newsletter
    about: Subscribe to our newsletter for updates
